### ISSUE TITLE
[Marker.io] flag box is empty also the dropdown are empty on clicking this flag field

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#1]
[![Screenshot_2024-10-08_07-00-06.png](https://mrkr.io/s/6704d876b174a83505df97f2/2)](https://mrkr.io/s/6704d876b174a83505df97f2/0)

Steps to reproduce:
1) click the flag field box on contact page

Actual result: it does not show anything
2) dropdown is also empty

Expected result: please fix this

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/6704d876b174a83505df97f9?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/contact](https://na13-prezzee.webflow.io/contact)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6704d876b174a83505df97f9?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 129.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

---
**Attached files:** 

**-** [image.png (51.6KB)](https://files.marker.io/f/65fb7ea27d9ebfe5c74463e7/6704d876b174a83505df97f6)

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6704d876b174a83505df97f9?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io

**Comment by vinod-ku1989** [comment]
issue is still there @Druhin13 .why is this one closed:
![image](https://github.com/user-attachments/assets/b9f342f4-c4a3-43ca-bc69-6b5655107f79)

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6704d876b174a83505df97f9?advanced=1) - This issue was marked as **❗️ Open** in Marker.io

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6704d876b174a83505df97f9?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io

**Comment by vinod-ku1989** [comment]
still not fixed properly. please do not close the issues that were raised by me :)
just add "fixed" or "retest needed" labels after fixing.
1) notice the blank modal. values are highlighted only on hovering over them
2) phone format is not shown next to "US" value. it is shown only if the user selects some other value from dropdown

video: https://go.screenpal.com/watch/cZX61NncPDO

![image](https://github.com/user-attachments/assets/32f58b45-8332-49fb-a260-31c72a9956dc)

@Druhin13

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6704d876b174a83505df97f9?advanced=1) - This issue was marked as **❗️ Open** in Marker.io

**Comment by vinod-ku1989** [comment]
strange inconsisten behaviour:
on firefox, shows the flag and in chrome, 2 letter code
![image](https://github.com/user-attachments/assets/5a7ea1e0-bbca-4a41-af53-bc33fd5b5f65)

chrome:
![image](https://github.com/user-attachments/assets/23a7996a-9bc7-49de-8943-a58f80ef774e)

@Druhin13

**Comment by Druhin13** [comment]
The current decision is to maintain the intended behavior.

> "Emoji flags are supported on all major platforms except for Windows, which displays two-letter country codes instead of emoji flag images. Windows has never supported any national flag emoji designs."

We may consider updating the flags to use images instead of emojis in order to ensure consistency across devices. However, since this change does not currently affect any expected functionalities, it will be addressed in phase 2.

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6704d876b174a83505df97f9?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
