### ISSUE TITLE
[Marker.io] (Mobile) bullet list alphabets not shown properly

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#101]
[![Screenshot_2024-11-08_00-56-55.png](https://img.marker.io/s/672d61d7b150a67b8458c13d/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJkNjFkN2IxNTBhNjdiODQ1OGMxM2QiLCJvd25lclJlc291cmNlVXVpZCI6ImNhZjRmZDBhLTJhMjYtNDEwYi04YmE2LTE2ZmUyZDgxYTljOSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTAyNzQxNSwiZXhwIjoxNzM4ODAzNDE1fQ.g2IuGVvTEolUUF3P4pmOrq7zOGtEcWPkXXZ4v-tg6YQ)](https://img.marker.io/s/672d61d7b150a67b8458c13d/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJkNjFkN2IxNTBhNjdiODQ1OGMxM2QiLCJvd25lclJlc291cmNlVXVpZCI6ImNhZjRmZDBhLTJhMjYtNDEwYi04YmE2LTE2ZmUyZDgxYTljOSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTAyNzQxNSwiZXhwIjoxNzM4ODAzNDE1fQ.g2IuGVvTEolUUF3P4pmOrq7zOGtEcWPkXXZ4v-tg6YQ)

Steps to reproduce:
1) notice subsections under section 1

Actual result: a, b are not shown properly

Expected result: please fix this

---

**Reported by:** Vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672d61d7b150a67b8458c140?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/legal/gdpr](https://na13-prezzee.webflow.io/en-us/legal/gdpr)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672d61d7b150a67b8458c140?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Safari 18.0.1</td></tr><tr><td><strong>Screen Size</strong></td><td>375 x 812</td></tr><tr><td><strong>OS</strong></td><td>iOS 18.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>375 x 710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;3x</td></tr></table>

**Comment by vinod-ku1989** [comment]
actual screenshot:
https://drive.google.com/file/d/1blaTvX8NmYMRSTgqwAEEVKrzOuPEzdwt/view?usp=sharing

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672d61d7b150a67b8458c140?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
