### ISSUE TITLE
[Marker.io] Mobile: no is not shown at one place on mobile devices

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#102]
[![Screenshot_2024-11-08_01-06-40.png](https://img.marker.io/s/672d6420b150a67b8458cadb/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJkNjQyMGIxNTBhNjdiODQ1OGNhZGIiLCJvd25lclJlc291cmNlVXVpZCI6ImNhZjRmZDBhLTJhMjYtNDEwYi04YmE2LTE2ZmUyZDgxYTljOSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTAyODAwMCwiZXhwIjoxNzM4ODA0MDAwfQ.F1IfZKUra4mnUtZxyeinQgV_DSiPhX8dEJjvQ6zfM0I)](https://img.marker.io/s/672d6420b150a67b8458cadb/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJkNjQyMGIxNTBhNjdiODQ1OGNhZGIiLCJvd25lclJlc291cmNlVXVpZCI6ImNhZjRmZDBhLTJhMjYtNDEwYi04YmE2LTE2ZmUyZDgxYTljOSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTAyODAwMCwiZXhwIjoxNzM4ODA0MDAwfQ.F1IfZKUra4mnUtZxyeinQgV_DSiPhX8dEJjvQ6zfM0I)

Steps to reproduce:
1) notice ACN

Actual result: there is no no next to it which is shown on desktop

Expected result:please please fix this

---

**Reported by:** Vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672d6420b150a67b8458cade?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/legal/privacy-and-data-policy](https://na13-prezzee.webflow.io/en-us/legal/privacy-and-data-policy)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672d6420b150a67b8458cade?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Safari 18.0.1</td></tr><tr><td><strong>Screen Size</strong></td><td>375 x 812</td></tr><tr><td><strong>OS</strong></td><td>iOS 18.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>375 x 628</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;3x</td></tr></table>

**Comment by vinod-ku1989** [comment]
also observed on tablet devices(bboth portrait and landscape mde)
resolution:
1) 768*1024
2)1024*768

**Comment by Druhin13** [comment]
Future ref:

Safari was automatically considering them as a phone/mobile number / hence: the text converted into a link (:visible)

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672d6420b150a67b8458cade?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
