### ISSUE TITLE
[Marker.io] Mobile: numbering list not shown properly

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#103]
[![Screenshot_2024-11-08_01-08-54.png](https://img.marker.io/s/672d64a6fe57c8b97a243037/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJkNjRhNmZlNTdjOGI5N2EyNDMwMzciLCJvd25lclJlc291cmNlVXVpZCI6ImNhZjRmZDBhLTJhMjYtNDEwYi04YmE2LTE2ZmUyZDgxYTljOSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTAyODEzNCwiZXhwIjoxNzM4ODA0MTM0fQ.H0E5SFe9yjRIPER0dxHyfQU8rCR1dEB_ALK4S3E4Nmc)](https://img.marker.io/s/672d64a6fe57c8b97a243037/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJkNjRhNmZlNTdjOGI5N2EyNDMwMzciLCJvd25lclJlc291cmNlVXVpZCI6ImNhZjRmZDBhLTJhMjYtNDEwYi04YmE2LTE2ZmUyZDgxYTljOSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTAyODEzNCwiZXhwIjoxNzM4ODA0MTM0fQ.H0E5SFe9yjRIPER0dxHyfQU8rCR1dEB_ALK4S3E4Nmc)

Steps to reproduce:
1) go to section 2 and 3
2) notice the numbering or alphabetical list

Actual result: numbers or alphabets are not shown properly

Expected result: please fix

---

**Reported by:** Vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672d64a6fe57c8b97a24303a?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/legal/privacy-and-data-policy](https://na13-prezzee.webflow.io/en-us/legal/privacy-and-data-policy)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672d64a6fe57c8b97a24303a?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Safari 18.0.1</td></tr><tr><td><strong>Screen Size</strong></td><td>375 x 812</td></tr><tr><td><strong>OS</strong></td><td>iOS 18.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>375 x 710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;3x</td></tr></table>

**Comment by vinod-ku1989** [comment]
actual screenshot:
https://drive.google.com/file/d/1Nk2A8CMKcva2AC-Sp9HYy_b5ZiiGcfA8/view?usp=sharing

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672d64a6fe57c8b97a24303a?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
