### ISSUE TITLE
[Marker.io] CTAS missing from mobile menu 

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#104]
[![Screenshot_2024-11-08_01-27-44.png](https://img.marker.io/s/672d6910bb17431117a3c44d/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJkNjkxMGJiMTc0MzExMTdhM2M0NGQiLCJvd25lclJlc291cmNlVXVpZCI6IjdmOGQ3OTJjLWI4Y2EtNGJkZS05YWY4LTMyODNhNGI2OThlNyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6ImhvbGx5QHByZXp6ZWUuY29tIiwidGVhbVV1aWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOlsxMDEsMjUxLDEyNiwxNjIsMTI1LDE1OCwxOTEsMjI5LDE5OSw2OCw5OSwyMzFdfSwiaWF0IjoxNzMxMDI5MjY0LCJleHAiOjE3Mzg4MDUyNjR9.WtRgDI5EilaqDjbLtyZzD0OVb34rjHJBcGLisu-WW48)](https://img.marker.io/s/672d6910bb17431117a3c44d/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJkNjkxMGJiMTc0MzExMTdhM2M0NGQiLCJvd25lclJlc291cmNlVXVpZCI6IjdmOGQ3OTJjLWI4Y2EtNGJkZS05YWY4LTMyODNhNGI2OThlNyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6ImhvbGx5QHByZXp6ZWUuY29tIiwidGVhbVV1aWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOlsxMDEsMjUxLDEyNiwxNjIsMTI1LDE1OCwxOTEsMjI5LDE5OSw2OCw5OSwyMzFdfSwiaWF0IjoxNzMxMDI5MjY0LCJleHAiOjE3Mzg4MDUyNjR9.WtRgDI5EilaqDjbLtyZzD0OVb34rjHJBcGLisu-WW48)

Please add get started and book a demo CTAS 

---

**Reported by:** Holly  (holly@prezzee.com) - [Contact via Marker.io](https://app.marker.io/i/672d6910bb17431117a3c450?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us](https://na13-prezzee.webflow.io/en-us)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672d6910bb17431117a3c450?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Chrome Mobile 130.0.6723.90</td></tr><tr><td><strong>Screen Size</strong></td><td>402 x 874</td></tr><tr><td><strong>OS</strong></td><td>iOS 18.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>402 x 684</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;3x</td></tr></table>

**Comment by vinod-ku1989** [comment]
@Druhin13 i checked this on mobile.  this request is still not implemented.

( although mobile figma does not show thesebuttons).

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672d6910bb17431117a3c450?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
