### ISSUE TITLE
[Marker.io] Mobile:3 boxes do not have design like background 

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#121]
[![Screenshot_2024-11-08_10-29-37.png](https://img.marker.io/s/672de811f4f1cce61d46b5be/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJkZTgxMWY0ZjFjY2U2MWQ0NmI1YmUiLCJvd25lclJlc291cmNlVXVpZCI6Ijc5Y2I0ZGNjLTM1ZjAtNGZhMC1iZWQyLTQ4MzY5MWFhN2QxYiIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTA2MTc3NywiZXhwIjoxNzM4ODM3Nzc3fQ.edR6r8PFs-MsjG8JCaQ-JWjBGVbrSEa2WeIzmelf-iA)](https://img.marker.io/s/672de811f4f1cce61d46b5be/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJkZTgxMWY0ZjFjY2U2MWQ0NmI1YmUiLCJvd25lclJlc291cmNlVXVpZCI6Ijc5Y2I0ZGNjLTM1ZjAtNGZhMC1iZWQyLTQ4MzY5MWFhN2QxYiIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTA2MTc3NywiZXhwIjoxNzM4ODM3Nzc3fQ.edR6r8PFs-MsjG8JCaQ-JWjBGVbrSEa2WeIzmelf-iA)

Steps to reproduce:
1)notice the 3 boxes , api integration, campaigns and preset for business
2) compare with figma

Actual result: figma shows they have some designs

Expected result: please check this. Desktop design do not have these designs in the background of boxes

---

**Reported by:** Vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672de811f4f1cce61d46b5c1?advanced=1&comments=1)

**Source URL:** [https://wf-b.stg.prezzee.com/en-us/pricing](https://wf-b.stg.prezzee.com/en-us/pricing)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672de811f4f1cce61d46b5c1?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Safari 18.0.1</td></tr><tr><td><strong>Screen Size</strong></td><td>375 x 812</td></tr><tr><td><strong>OS</strong></td><td>iOS 18.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>375 x 628</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;3x</td></tr></table>

**Comment by vinod-ku1989** [comment]
@ckosik1 please check this ..and then assign to @Druhin13 if somthing needs to be done here
both designs are not consistent (with respect to those 3 boxes).(in mobile, those boxes have designs in background and do not have simple plain background)

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672de811f4f1cce61d46b5c1?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
