### ISSUE TITLE
[Marker.io] "Our journey" heading and "text" below the progress bar is in red ( design discrepancy)

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#125]
[![Screenshot_2024-11-08_11-17-38.png](https://img.marker.io/s/672df352373f666835eea72d/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJkZjM1MjM3M2Y2NjY4MzVlZWE3MmQiLCJvd25lclJlc291cmNlVXVpZCI6ImRmNzc2ZTVmLTc1MmUtNGJiZC05MDUwLTYyOTEzYzQ4NTM1ZCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTA2NDY1OCwiZXhwIjoxNzM4ODQwNjU4fQ.vJOQLPWpApBz37Ejf8rVFlLpg4zDeB86WobBWfWdGRQ)](https://img.marker.io/s/672df352373f666835eea72d/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJkZjM1MjM3M2Y2NjY4MzVlZWE3MmQiLCJvd25lclJlc291cmNlVXVpZCI6ImRmNzc2ZTVmLTc1MmUtNGJiZC05MDUwLTYyOTEzYzQ4NTM1ZCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTA2NDY1OCwiZXhwIjoxNzM4ODQwNjU4fQ.vJOQLPWpApBz37Ejf8rVFlLpg4zDeB86WobBWfWdGRQ)

Steps to reproduce:
1) go to "Our journey" section
2) notice the heading and the text below the years
3)compare both desktop and mobile

Actual result: both have different colors

Expected result: currently the one shown on mobile is implemented.
not sure if current behaviour is correct one.

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672df352373f666835eea730?advanced=1&comments=1)

**Source URL:** [https://wf-b.stg.prezzee.com/en-us/sustainability](https://wf-b.stg.prezzee.com/en-us/sustainability)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672df352373f666835eea730?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1707 x 801</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;0.800000011920929x</td></tr></table>

**Comment by vinod-ku1989** [comment]
@ckosik1 please check this.
if this current behaviour is not correct and needs to be addressed, assign it to @Druhin13 .

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672df352373f666835eea730?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
