### ISSUE TITLE
[Marker.io] button not visible completely and also the arrow button is not there

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#134]
[![Screenshot_2024-11-08_14-08-10.png](https://img.marker.io/s/672e1b4a87ae06d920c4fdd4/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJlMWI0YTg3YWUwNmQ5MjBjNGZkZDQiLCJvd25lclJlc291cmNlVXVpZCI6ImRmNzc2ZTVmLTc1MmUtNGJiZC05MDUwLTYyOTEzYzQ4NTM1ZCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTA3NDg5MCwiZXhwIjoxNzM4ODUwODkwfQ.12xXY_ZX3gn9b5b3-h2nGBfPz0Psql4I41Kw6XbWWiU)](https://img.marker.io/s/672e1b4a87ae06d920c4fdd4/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJlMWI0YTg3YWUwNmQ5MjBjNGZkZDQiLCJvd25lclJlc291cmNlVXVpZCI6ImRmNzc2ZTVmLTc1MmUtNGJiZC05MDUwLTYyOTEzYzQ4NTM1ZCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTA3NDg5MCwiZXhwIjoxNzM4ODUwODkwfQ.12xXY_ZX3gn9b5b3-h2nGBfPz0Psql4I41Kw6XbWWiU)

Steps to reproduce:
1) notice the buttons shown on brand page
2) notice the right most button and compare with figma

Actual result:
1) it is not visible completely
2)arrow icon is not there 

Expected result: please fix this.(according to figma)

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672e1b4a87ae06d920c4fdd7?advanced=1&comments=1)

**Source URL:** [https://wf-b.stg.prezzee.com/en-us/brands](https://wf-b.stg.prezzee.com/en-us/brands)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672e1b4a87ae06d920c4fdd7?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
1) issue is still there on new staging site too
https://stg.prezzee.com/business/m/en-us/brands

2) buttons are still not getting highlighted (when user clicks on different buttons like eatingin , eating out) etc
@Druhin13

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672e1b4a87ae06d920c4fdd7?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
