### ISSUE TITLE
[Marker.io] "Get started" button missing on card popop

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#139]
[![Screenshot_2024-11-08_14-20-51.png](https://img.marker.io/s/672e1e432148df78633a4a3f/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJlMWU0MzIxNDhkZjc4NjMzYTRhM2YiLCJvd25lclJlc291cmNlVXVpZCI6ImRmNzc2ZTVmLTc1MmUtNGJiZC05MDUwLTYyOTEzYzQ4NTM1ZCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTA3NTY1MSwiZXhwIjoxNzM4ODUxNjUxfQ.2AawKF7GtPSwDJXlIAgPnAUOQX28LinePt3ggv5WswM)](https://img.marker.io/s/672e1e432148df78633a4a3f/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJlMWU0MzIxNDhkZjc4NjMzYTRhM2YiLCJvd25lclJlc291cmNlVXVpZCI6ImRmNzc2ZTVmLTc1MmUtNGJiZC05MDUwLTYyOTEzYzQ4NTM1ZCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTA3NTY1MSwiZXhwIjoxNzM4ODUxNjUxfQ.2AawKF7GtPSwDJXlIAgPnAUOQX28LinePt3ggv5WswM)

Steps to reproduce:
1) scroll down and click on any card
2) compare with figma

Actual result: figma shows "Get started" button in desktop design but is not there in mobile design

Expected result:
not sure what is the correct behaviour. whether it should be there or not..

please check and implement if it should be there

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672e1e432148df78633a4a42?advanced=1&comments=1)

**Source URL:** [https://wf-b.stg.prezzee.com/en-us/brands](https://wf-b.stg.prezzee.com/en-us/brands)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672e1e432148df78633a4a42?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
@ckosik1 please confirm if it should be there or not.

if yes, then @Druhin13 please implement this

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672e1e432148df78633a4a42?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
