### ISSUE TITLE
[Marker.io] wierd behaviour of faq on "au" version

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#147]
[![Screenshot_2024-11-08_17-47-27.png](https://img.marker.io/s/672e4eafe7963b0e147621a5/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJlNGVhZmU3OTYzYjBlMTQ3NjIxYTUiLCJvd25lclJlc291cmNlVXVpZCI6Ijk4NGE2NzQ5LWViZjUtNDYyZC05NjdjLWFkNTM1NjdkMDNmOSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTA4ODA0NywiZXhwIjoxNzM4ODY0MDQ3fQ.2z8FoOOTlj3HbR3qC_OBrWaGKFqleLoH8SU1fz9hQp0)](https://img.marker.io/s/672e4eafe7963b0e147621a5/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJlNGVhZmU3OTYzYjBlMTQ3NjIxYTUiLCJvd25lclJlc291cmNlVXVpZCI6Ijk4NGE2NzQ5LWViZjUtNDYyZC05NjdjLWFkNTM1NjdkMDNmOSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTA4ODA0NywiZXhwIjoxNzM4ODY0MDQ3fQ.2z8FoOOTlj3HbR3qC_OBrWaGKFqleLoH8SU1fz9hQp0)

Steps to reproduce:
1) check the faq on desktop
2) check the faq section on mobile
for "prepaid visacard

Actual result:
desktop does not show any faq, mobile shows already opened all accordions in the faq

Expected result:
please fix

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672e4eafe7963b0e147621a8?advanced=1&comments=1)

**Source URL:** [https://wf-b.stg.prezzee.com/en-au/prepaid-visa-card](https://wf-b.stg.prezzee.com/en-au/prepaid-visa-card)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672e4eafe7963b0e147621a8?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 132.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 615</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
mobile: iphone 12 mini, ios, safari
https://drive.google.com/file/d/1Grr59MUZ1YhroJNGAv_enCdZNgOijCq9/view?usp=sharing

**Comment by Druhin13** [comment]
The issues regarding the visibility of the FAQ section have been resolved across the entire site. Previously, the FAQs were not properly configured in the CMS.

Now, if a page does not have an FAQ section, this is the intended behavior, depending on whether any FAQs are available in the CMS for that specific page.

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672e4eafe7963b0e147621a8?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
