### ISSUE TITLE
[Marker.io] menus does not  expand on hovering over them. click is required

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#149]
[![Screenshot_2024-11-09_04-32-04.png](https://img.marker.io/s/672ee5c4373f666835f5e157/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJlZTVjNDM3M2Y2NjY4MzVmNWUxNTciLCJvd25lclJlc291cmNlVXVpZCI6ImRmNzc2ZTVmLTc1MmUtNGJiZC05MDUwLTYyOTEzYzQ4NTM1ZCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTEyNjcyNCwiZXhwIjoxNzM4OTAyNzI0fQ.TrenVlCToMJiiDkjmjBEXTute1L-Cr996J-dX7NgvvI)](https://img.marker.io/s/672ee5c4373f666835f5e157/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJlZTVjNDM3M2Y2NjY4MzVmNWUxNTciLCJvd25lclJlc291cmNlVXVpZCI6ImRmNzc2ZTVmLTc1MmUtNGJiZC05MDUwLTYyOTEzYzQ4NTM1ZCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTEyNjcyNCwiZXhwIjoxNzM4OTAyNzI0fQ.TrenVlCToMJiiDkjmjBEXTute1L-Cr996J-dX7NgvvI)

Steps to reproduce:
1) hover over menus like "prezzee for" , "solutions"

Actual result: submenus are not shown. click is required to see those

Expected result: please fix this.
(not sure if current behaviour is changed or implemented based  on clients feedback)

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672ee5c4373f666835f5e15a?advanced=1&comments=1)

**Source URL:** [https://wf-b.stg.prezzee.com/en-us/search](https://wf-b.stg.prezzee.com/en-us/search)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672ee5c4373f666835f5e15a?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
https://go.screenpal.com/watch/cZXQ1HncN9e

heres the video

**Comment by Druhin13** [comment]
intended behavior

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672ee5c4373f666835f5e15a?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
