### ISSUE TITLE
[Marker.io] heading is "Our features" but in figma it is "Key features"

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#157]
[![Screenshot_2024-11-10_03-49-33.png](https://img.marker.io/s/67302d4ddc24287b61ee47c6/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzMwMmQ0ZGRjMjQyODdiNjFlZTQ3YzYiLCJvd25lclJlc291cmNlVXVpZCI6ImRmNzc2ZTVmLTc1MmUtNGJiZC05MDUwLTYyOTEzYzQ4NTM1ZCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTIxMDU3MywiZXhwIjoxNzM4OTg2NTczfQ.5Yns7XBsWSi-17au7hdUFdszP1lDD3l3kiLpIYB-hYk)](https://img.marker.io/s/67302d4ddc24287b61ee47c6/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzMwMmQ0ZGRjMjQyODdiNjFlZTQ3YzYiLCJvd25lclJlc291cmNlVXVpZCI6ImRmNzc2ZTVmLTc1MmUtNGJiZC05MDUwLTYyOTEzYzQ4NTM1ZCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTIxMDU3MywiZXhwIjoxNzM4OTg2NTczfQ.5Yns7XBsWSi-17au7hdUFdszP1lDD3l3kiLpIYB-hYk)

Steps to reproduce:
1)check the "Our features" heading
2) compare with figma

Actual result:
it is "Key features" in figma

Expected result: if current behaviour is latest one, please ignore and close
else fix this 

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/67302d4ddc24287b61ee47c9?advanced=1&comments=1)

**Source URL:** [https://wf-b.stg.prezzee.com/en-us/corporate-gifting-solutions/business-portal?marker=true](https://wf-b.stg.prezzee.com/en-us/corporate-gifting-solutions/business-portal?marker=true)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/67302d4ddc24287b61ee47c9?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
same thing observedon :
https://wf-b.stg.prezzee.com/en-us/corporate-gifting-solutions/campaigns (Campaigns)
https://wf-b.stg.prezzee.com/en-us/corporate-gifting-solutions/api (API)

**Comment by Druhin13** [comment]
Not entirely sure which one's correct | as both were approved by the client
Closing this but flagging under content

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/67302d4ddc24287b61ee47c9?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
