### ISSUE TITLE
[Marker.io] figma shows a video in header area but actual page has image

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#158]
[![Screenshot_2024-11-10_03-51-32.png](https://img.marker.io/s/67302dc4eb296aa2d5da18cc/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzMwMmRjNGViMjk2YWEyZDVkYTE4Y2MiLCJvd25lclJlc291cmNlVXVpZCI6ImRmNzc2ZTVmLTc1MmUtNGJiZC05MDUwLTYyOTEzYzQ4NTM1ZCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTIxMDY5MiwiZXhwIjoxNzM4OTg2NjkyfQ.BNXjLHC4pdpcr3Pe32OHudW8jKO6UgQIoMS4MPVcayI)](https://img.marker.io/s/67302dc4eb296aa2d5da18cc/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzMwMmRjNGViMjk2YWEyZDVkYTE4Y2MiLCJvd25lclJlc291cmNlVXVpZCI6ImRmNzc2ZTVmLTc1MmUtNGJiZC05MDUwLTYyOTEzYzQ4NTM1ZCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTIxMDY5MiwiZXhwIjoxNzM4OTg2NjkyfQ.BNXjLHC4pdpcr3Pe32OHudW8jKO6UgQIoMS4MPVcayI)

Steps to reproduce:
check the header area image and compare with figma

Actual result:figma shows a video with play button but actual page has image

Expected result:
if current behaviour is correct and latest one, please ignore and close else add the video please

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/67302dc4eb296aa2d5da18cf?advanced=1&comments=1)

**Source URL:** [https://wf-b.stg.prezzee.com/en-us/corporate-gifting-solutions/business-portal?marker=true](https://wf-b.stg.prezzee.com/en-us/corporate-gifting-solutions/business-portal?marker=true)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/67302dc4eb296aa2d5da18cf?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
also observed on:
https://wf-b.stg.prezzee.com/en-us/corporate-gifting-solutions/campaigns

@Druhin13

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/67302dc4eb296aa2d5da18cf?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
