### ISSUE TITLE
[Marker.io] "related case studies" section is missing

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#160]
[![Screenshot_2024-11-10_03-57-56.png](https://img.marker.io/s/67302f44373f666835f8fe50/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzMwMmY0NDM3M2Y2NjY4MzVmOGZlNTAiLCJvd25lclJlc291cmNlVXVpZCI6ImRmNzc2ZTVmLTc1MmUtNGJiZC05MDUwLTYyOTEzYzQ4NTM1ZCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTIxMTA3NiwiZXhwIjoxNzM4OTg3MDc2fQ.qBenxcZORG2-pd5Rzmq4iRioLuQAUrp33RB46XUmb-o)](https://img.marker.io/s/67302f44373f666835f8fe50/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzMwMmY0NDM3M2Y2NjY4MzVmOGZlNTAiLCJvd25lclJlc291cmNlVXVpZCI6ImRmNzc2ZTVmLTc1MmUtNGJiZC05MDUwLTYyOTEzYzQ4NTM1ZCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTIxMTA3NiwiZXhwIjoxNzM4OTg3MDc2fQ.qBenxcZORG2-pd5Rzmq4iRioLuQAUrp33RB46XUmb-o)

Steps to reproduce:
1) check the section above faqs
2) compare with figma

Actual result:
related case studies section is missing

Expected result:
if current behaviour is latest one and is correct, then ignore else fix this please

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/67302f44373f666835f8fe53?advanced=1&comments=1)

**Source URL:** [https://wf-b.stg.prezzee.com/en-us/corporate-gifting-solutions/business-portal?marker=true](https://wf-b.stg.prezzee.com/en-us/corporate-gifting-solutions/business-portal?marker=true)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/67302f44373f666835f8fe53?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
issue is applicable for other 2 pages too:
https://wf-b.stg.prezzee.com/en-us/corporate-gifting-solutions/campaigns (Campaigns)
https://wf-b.stg.prezzee.com/en-us/corporate-gifting-solutions/api (API)

@Druhin13

**Comment by Druhin13** [comment]
Hidden for Phase 1

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/67302f44373f666835f8fe53?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
