### ISSUE TITLE
(mobile) all the 4 options are shown directly below the "animation

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#174]
[![Screenshot_2024-11-10_08-21-21.png](https://img.marker.io/s/67306d01373f666835f97b1e/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzMwNmQwMTM3M2Y2NjY4MzVmOTdiMWUiLCJvd25lclJlc291cmNlVXVpZCI6IjY1NWRmNjFhNTFhODQ1MjhjMzRlZjkwOSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTIyNjg4MSwiZXhwIjoxNzM5MDAyODgxfQ.tvltHAJUQ5JulR0PVeoDU5lBgqoVbdEEfDvk_vgumu0)](https://img.marker.io/s/67306d01373f666835f97b1e/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzMwNmQwMTM3M2Y2NjY4MzVmOTdiMWUiLCJvd25lclJlc291cmNlVXVpZCI6IjY1NWRmNjFhNTFhODQ1MjhjMzRlZjkwOSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTIyNjg4MSwiZXhwIjoxNzM5MDAyODgxfQ.tvltHAJUQ5JulR0PVeoDU5lBgqoVbdEEfDvk_vgumu0)

Steps to reproduce:
1) scroll down and notice the 4 options
1 to 4
2) compare with figma

Actual result: allthe options are shown one below the other but in figma , design is different

Expected result:if current one is correct, then please ignore and close this

---

**Reported by:** Vinod (vinod@na.studio)

**Source URL:** [https://wf-b.stg.prezzee.com/en-us](https://wf-b.stg.prezzee.com/en-us)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/67306d01373f666835f97b21?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
behaviour on mobile:
![image](https://github.com/user-attachments/assets/4c2d932f-bda9-4a89-8cf0-fde38d82ba94)

**Comment by Druhin13** [comment]
discussed | we might potentially update this in Phase 2

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/67306d01373f666835f97b21?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
