### ISSUE TITLE
[Marker.io] Mobile: menu bar does not match figma for 404 page

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#185]
[![Screenshot_2024-11-10_13-56-53.png](https://img.marker.io/s/6730bba5373f666835fa3c5e/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzMwYmJhNTM3M2Y2NjY4MzVmYTNjNWUiLCJvd25lclJlc291cmNlVXVpZCI6IjFkZTU1YWE1LTg1NTItNDFjZS04OTQ3LTEzZDcwNWMyM2VkZSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTI0NzAxMywiZXhwIjoxNzM5MDIzMDEzfQ.IqLE9UYYQ66C5l4-zi-jgyF_lxzD1_pTdQjZ4px0VA8)](https://img.marker.io/s/6730bba5373f666835fa3c5e/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzMwYmJhNTM3M2Y2NjY4MzVmYTNjNWUiLCJvd25lclJlc291cmNlVXVpZCI6IjFkZTU1YWE1LTg1NTItNDFjZS04OTQ3LTEzZDcwNWMyM2VkZSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTI0NzAxMywiZXhwIjoxNzM5MDIzMDEzfQ.IqLE9UYYQ66C5l4-zi-jgyF_lxzD1_pTdQjZ4px0VA8)

Steps to reproduce:
Compare menu bar on 404 and compare with figma

Actual result: does not match figma

Expected result: please fix

---

**Reported by:** Vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/6730bba5373f666835fa3c61?advanced=1&comments=1)

**Source URL:** [https://wf-b.stg.prezzee.com/en-us/whatever](https://wf-b.stg.prezzee.com/en-us/whatever)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6730bba5373f666835fa3c61?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Safari 18.0.1</td></tr><tr><td><strong>Screen Size</strong></td><td>375 x 812</td></tr><tr><td><strong>OS</strong></td><td>iOS 18.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>375 x 628</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;3x</td></tr></table>

**Comment by vinod-ku1989** [comment]
also applicable for  404 desktop page.
@Druhin13

**Comment by Druhin13** [comment]
this would not be worked on
potential nav update on phase 2, once we work on the gift customizer page

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6730bba5373f666835fa3c61?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
