### ISSUE TITLE
3 column section on home is distorted now

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#192]
[![Screenshot_2024-11-12_02-48-07.png](https://img.marker.io/s/6732c1e7e732491c2bbe9084/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzMyYzFlN2U3MzI0OTFjMmJiZTkwODQiLCJvd25lclJlc291cmNlVXVpZCI6IjY1NWRmNjFhNTFhODQ1MjhjMzRlZjkwOSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTM3OTY4NywiZXhwIjoxNzM5MTU1Njg3fQ.TVtyatLAY4hsrNn4c9SX9izmttTD8lRHZ1QuPXenioM)](https://img.marker.io/s/6732c1e7e732491c2bbe9084/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzMyYzFlN2U3MzI0OTFjMmJiZTkwODQiLCJvd25lclJlc291cmNlVXVpZCI6IjY1NWRmNjFhNTFhODQ1MjhjMzRlZjkwOSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMTM3OTY4NywiZXhwIjoxNzM5MTU1Njg3fQ.TVtyatLAY4hsrNn4c9SX9izmttTD8lRHZ1QuPXenioM)

Steps to reproduce:
check the 3 column section

Actual result: distorted now

Expected result: please fix. some change/fix has caused this

---

**Reported by:** Vinod (vinod@na.studio)

**Source URL:** [https://wf-b.stg.prezzee.com/en-us](https://wf-b.stg.prezzee.com/en-us)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6732c1e7e732491c2bbe9087?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
@Druhin13 issue present even on new url
https://stg.prezzee.com/business/m/en-us

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6732c1e7e732491c2bbe9087?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
