### ISSUE TITLE
[Marker.io] [localization issue 3] sidebar is not shown when language is unsupported and region is unsupported

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#212]
[![Screenshot_2024-11-21_08-49-18.png](https://img.marker.io/s/673ef40e021d74c049387bf5/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzNlZjQwZTAyMWQ3NGMwNDkzODdiZjUiLCJvd25lclJlc291cmNlVXVpZCI6ImUxOWVlNWY0LTc1ZGMtNDI4Mi05YmQ0LWVlYjg0NDc2MDdmYSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMjE3ODk1OCwiZXhwIjoxNzM5OTU0OTU4fQ.aADb-9I0KHukTfxSiL33PzoZv00Lrz2QSgdB1eqTo84)](https://img.marker.io/s/673ef40e021d74c049387bf5/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzNlZjQwZTAyMWQ3NGMwNDkzODdiZjUiLCJvd25lclJlc291cmNlVXVpZCI6ImUxOWVlNWY0LTc1ZGMtNDI4Mi05YmQ0LWVlYjg0NDc2MDdmYSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMjE3ODk1OCwiZXhwIjoxNzM5OTU0OTU4fQ.aADb-9I0KHukTfxSiL33PzoZv00Lrz2QSgdB1eqTo84)

Steps to reproduce:
1) clear cache/historY
2) set browser langauge to german
3) hit the url :
https://stg.prezzee.com/business/m/en-gb/brands
(accessing from India location)

4) notice that it correctly redirects to US version ( according to logic) . there is slight delay too in this
5) wait for sidebar

Actual result: sidebar does not appear

Expected result:

check the rule 4b in the document. it should have shown the sidebar in this scenario

https://go.screenpal.com/watch/cZXrjEnVxmG

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/673ef40e021d74c049387bf8?advanced=1&comments=1)

**Source URL:** [https://stg.prezzee.com/business/m/en-us/brands?marker=true](https://stg.prezzee.com/business/m/en-us/brands?marker=true)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/673ef40e021d74c049387bf8?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 132.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1354 x 609</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
this should work in other 2 scenarios also since the user is first time user without stored preference:
a) when browser langauge is different(e.g: german) and region is supported (e.g: Australia)
**note:**  redirection was correct in this scenario. sidebar should appear with correct messaging.

b) when browser langauge is different(e.g: german) and region is unsupported (e.g: Finland)
note: redirection was correct in this sccenario ( to en-us locale) , sidebar should appear with correct messaging.
since there is no stored preference.

@Druhin13

**Comment by Druhin13** [comment]
This is an interesting edge-case scenario. I believe the reason this occurred is that the user's preference was never removed from the browser's local storage. 

Currently, the locale preference is not saved in the cache or stored in cookies, which means it likely was never deleted. There is a discussion to be had about where this data should be stored, as this could change the behavior. However, for now, this situation falls under the intended behavior.

I will bring up the topic of storage with the rest of the team.

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/673ef40e021d74c049387bf8?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
