### ISSUE TITLE
[Marker.io] space is too much between "T" and "o" in "today"

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#49]
[![Screenshot_2024-11-06_04-48-39.png](https://img.marker.io/s/672af52721ad07e7cb87f35a/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJhZjUyNzIxYWQwN2U3Y2I4N2YzNWEiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg2ODUxOSwiZXhwIjoxNzM4NjQ0NTE5fQ.eRHdGv4QBUbMGEbaJ8bJqWF4qPDYp3UKKZUHjzt00Eg)](https://img.marker.io/s/672af52721ad07e7cb87f35a/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJhZjUyNzIxYWQwN2U3Y2I4N2YzNWEiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg2ODUxOSwiZXhwIjoxNzM4NjQ0NTE5fQ.eRHdGv4QBUbMGEbaJ8bJqWF4qPDYp3UKKZUHjzt00Eg)

Steps to reproduce:
1) scroll down to "start gifting today" section
2)notice "today" word
3) compare with figma

Actual result: space is more between "T" and "O"

Expected result: this needs to be  improved

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672af52721ad07e7cb87f35d?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-au/use-cases](https://na13-prezzee.webflow.io/en-au/use-cases)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672af52721ad07e7cb87f35d?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1517 x 712</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;0.8999999761581421x</td></tr></table>

**Comment by vinod-ku1989** [comment]
this component is present on all pages
