### ISSUE TITLE
[Marker.io] (mobile) size of cards is small as compared to figma

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#52]
[![Screenshot_2024-11-06_05-05-23.png](https://img.marker.io/s/672af9138879e3229c631c1c/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJhZjkxMzg4NzllMzIyOWM2MzFjMWMiLCJvd25lclJlc291cmNlVXVpZCI6ImU3YWZjYTI2LWNjMzItNDY1OC04ZDFlLTAwMDliODdjODJmMSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg2OTUyMywiZXhwIjoxNzM4NjQ1NTIzfQ.60l9-Lk-GhYHC6bsFyT_BwHmCZ190R5s_aiQu5MH-Qs)](https://img.marker.io/s/672af9138879e3229c631c1c/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJhZjkxMzg4NzllMzIyOWM2MzFjMWMiLCJvd25lclJlc291cmNlVXVpZCI6ImU3YWZjYTI2LWNjMzItNDY1OC04ZDFlLTAwMDliODdjODJmMSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg2OTUyMywiZXhwIjoxNzM4NjQ1NTIzfQ.60l9-Lk-GhYHC6bsFyT_BwHmCZ190R5s_aiQu5MH-Qs)

Steps to reproduce:
1) go to "customize your prezzee" section
2) notice the cards and compare with figma

Actual result: card size is small

Expected result: please check and fix this size

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672af9138879e3229c631c20?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/use-cases/employee-engagement](https://na13-prezzee.webflow.io/en-us/use-cases/employee-engagement)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672af9138879e3229c631c20?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Chrome Mobile 129.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>412 x 892</td></tr><tr><td><strong>OS</strong></td><td>Android 11.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>412 x 812</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2.625x</td></tr></table>

**Comment by vinod-ku1989** [comment]
fix on all use case pages.

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672af9138879e3229c631c20?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
