### ISSUE TITLE
[Marker.io] "book a demo" button is present in "success stories" section

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#53]
[![Screenshot_2024-11-06_05-12-38.png](https://img.marker.io/s/672afac67f76d67a5c9e839b/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJhZmFjNjdmNzZkNjdhNWM5ZTgzOWIiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg2OTk1OCwiZXhwIjoxNzM4NjQ1OTU4fQ.tsEn9HT-tK4CVV_egYO4eD7RtobTxGJjy1TiAafek70)](https://img.marker.io/s/672afac67f76d67a5c9e839b/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJhZmFjNjdmNzZkNjdhNWM5ZTgzOWIiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg2OTk1OCwiZXhwIjoxNzM4NjQ1OTU4fQ.tsEn9HT-tK4CVV_egYO4eD7RtobTxGJjy1TiAafek70)

Steps to reproduce:
1) go to success stories section
2)  notice the "book a demo" button
3) compare with figma

Actual result: book a demo button is used

Expected result: it should be "View case studies"

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672afac67f76d67a5c9e839e?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/use-cases/employee-engagement](https://na13-prezzee.webflow.io/en-us/use-cases/employee-engagement)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672afac67f76d67a5c9e839e?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1517 x 712</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;0.8999999761581421x</td></tr></table>

**Comment by vinod-ku1989** [comment]
issue is present on all use case pages.

**Comment by Druhin13** [comment]
Case Studies wouldn't be launched in Phase 1
Success Stories to be hidden

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672afac67f76d67a5c9e839e?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
