### ISSUE TITLE
[Marker.io] horizontal bar and the arrow button is missing in "success stories" section

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#54]
[![Screenshot_2024-11-06_05-14-40.png](https://img.marker.io/s/672afb406e9e095831964b9b/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJhZmI0MDZlOWUwOTU4MzE5NjRiOWIiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg3MDA4MCwiZXhwIjoxNzM4NjQ2MDgwfQ.nFc2USaPES8dBK7KaoaDebSQwg0fLG9rFxx1owwEX0k)](https://img.marker.io/s/672afb406e9e095831964b9b/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJhZmI0MDZlOWUwOTU4MzE5NjRiOWIiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg3MDA4MCwiZXhwIjoxNzM4NjQ2MDgwfQ.nFc2USaPES8dBK7KaoaDebSQwg0fLG9rFxx1owwEX0k)

Steps to reproduce:
1) go to success stories section
2) compare with figma

Actual result:
1) horizontal bar is missing
2) arrow button is missing

Expected result: if current behaviour is correct, please ignore else fix this please

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672afb406e9e095831964b9e?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/use-cases/employee-engagement](https://na13-prezzee.webflow.io/en-us/use-cases/employee-engagement)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672afb406e9e095831964b9e?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1517 x 712</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;0.8999999761581421x</td></tr></table>

**Comment by vinod-ku1989** [comment]
needs to be done on all use case pages.

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672afb406e9e095831964b9e?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
