### ISSUE TITLE
[Marker.io] "show more" link is missing

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#55]
[![Screenshot_2024-11-06_05-17-16.png](https://img.marker.io/s/672afbdcdb34a2b36eba7848/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJhZmJkY2RiMzRhMmIzNmViYTc4NDgiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg3MDIzNiwiZXhwIjoxNzM4NjQ2MjM2fQ.__QUUiDTlvC_o4b56Gt5_K7bC1HpD2svfHHMMToMmak)](https://img.marker.io/s/672afbdcdb34a2b36eba7848/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJhZmJkY2RiMzRhMmIzNmViYTc4NDgiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg3MDIzNiwiZXhwIjoxNzM4NjQ2MjM2fQ.__QUUiDTlvC_o4b56Gt5_K7bC1HpD2svfHHMMToMmak)

Steps to reproduce:
1) go to faq section
2) compare with figma

Actual result: "show more " link is missing

Expected result: figma is showing 8 accordions and then a "Show more" link

if current behaviour is correct, then please ignore else please implement this .

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672afbdcdb34a2b36eba784b?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/use-cases/employee-engagement](https://na13-prezzee.webflow.io/en-us/use-cases/employee-engagement)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672afbdcdb34a2b36eba784b?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1517 x 712</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;0.8999999761581421x</td></tr></table>

**Comment by vinod-ku1989** [comment]
missiing on all use case pages.

**Comment by Druhin13** [comment]
currently intended for phase 1
but could potentially be added in phase 2

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672afbdcdb34a2b36eba784b?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
