### ISSUE TITLE
[Marker.io] design discrepancies

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#56]
[![Screenshot_2024-11-06_05-40-02.png](https://img.marker.io/s/672b013221ad07e7cb882363/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJiMDEzMjIxYWQwN2U3Y2I4ODIzNjMiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg3MTYwMiwiZXhwIjoxNzM4NjQ3NjAyfQ.DoddxQp9KjVeTxDSkZE6MDAFNAXh7MIhoIoTcA3PWw8)](https://img.marker.io/s/672b013221ad07e7cb882363/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJiMDEzMjIxYWQwN2U3Y2I4ODIzNjMiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg3MTYwMiwiZXhwIjoxNzM4NjQ3NjAyfQ.DoddxQp9KjVeTxDSkZE6MDAFNAXh7MIhoIoTcA3PWw8)

Steps to reproduce:
check the desktop and mobile figma page for employee engagement
2) check the sections below "customize your prezzee" section

Actual result: there are different on both mobile and desktop

Expected result: please check this.
currently on moble, desktop design is shown.

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672b013221ad07e7cb882366?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/use-cases/employee-engagement](https://na13-prezzee.webflow.io/en-us/use-cases/employee-engagement)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672b013221ad07e7cb882366?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1517 x 712</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;0.8999999761581421x</td></tr></table>

**Comment by ckosik1** [comment]
Change in design

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672b013221ad07e7cb882366?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
