### ISSUE TITLE
[Marker.io] lot of empty space on higher resolutions

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#64]
[![Screenshot_2024-11-06_10-20-12.png](https://img.marker.io/s/672b42dc4e38671769ed7d97/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJiNDJkYzRlMzg2NzE3NjllZDdkOTciLCJvd25lclJlc291cmNlVXVpZCI6IjY3ZjUwMmEyLWZlNTAtNDFmNC1hNzk5LWJlODEyNjQ5MzQ4NCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg4ODQxMiwiZXhwIjoxNzM4NjY0NDEyfQ.w5tLz4CaqwbjfqSchepgst89QOsM0Mm_DnP57GAhX9E)](https://img.marker.io/s/672b42dc4e38671769ed7d97/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJiNDJkYzRlMzg2NzE3NjllZDdkOTciLCJvd25lclJlc291cmNlVXVpZCI6IjY3ZjUwMmEyLWZlNTAtNDFmNC1hNzk5LWJlODEyNjQ5MzQ4NCIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg4ODQxMiwiZXhwIjoxNzM4NjY0NDEyfQ.w5tLz4CaqwbjfqSchepgst89QOsM0Mm_DnP57GAhX9E)

Steps to reproduce:
1) check the use case pageon higher reesolutions like 2560*1920

Actual result:lot of empty spaces are there 
Expected result:

this needs to be improved.

https://go.screenpal.com/watch/cZX16FncG3K

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672b42dc4e38671769ed7d9a?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/use-cases](https://na13-prezzee.webflow.io/en-us/use-cases)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672b42dc4e38671769ed7d9a?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1920</td></tr><tr><td><strong>OS</strong></td><td>Windows 11 (15.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>2560 x 1785</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
this needs to be fixed on individual use case pages also like employee engagement etc.
there are lots of section where empty spaces are more ..**including the footer, menu nav bar**

https://go.screenpal.com/watch/cZX16FncG3K

**Comment by Druhin13** [comment]
intended
(explained in the chat)

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672b42dc4e38671769ed7d9a?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
