### ISSUE TITLE
[Marker.io] iOS issue: sections which have videos are showing the play controls instead of playing the video directly like on android or desktop

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#65]
[![Screenshot_2024-11-06_10-55-05.png](https://img.marker.io/s/672b4b09d6e3a230d68bcd51/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJiNGIwOWQ2ZTNhMjMwZDY4YmNkNTEiLCJvd25lclJlc291cmNlVXVpZCI6IjFmNTE1MzZkLTE0ZDQtNGE4Ni1iM2QzLWQ4MjBiNTBlYTk0MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg5MDUwNSwiZXhwIjoxNzM4NjY2NTA1fQ.MHDfDDeVG9ph2Kl5pIfW5uKTal7R1A20FEVDxVjlGXM)](https://img.marker.io/s/672b4b09d6e3a230d68bcd51/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJiNGIwOWQ2ZTNhMjMwZDY4YmNkNTEiLCJvd25lclJlc291cmNlVXVpZCI6IjFmNTE1MzZkLTE0ZDQtNGE4Ni1iM2QzLWQ4MjBiNTBlYTk0MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDg5MDUwNSwiZXhwIjoxNzM4NjY2NTA1fQ.MHDfDDeVG9ph2Kl5pIfW5uKTal7R1A20FEVDxVjlGXM)

Steps to reproduce:
1) scroll down to section where video are there
2) notice that player and play controls are shown
3) compare same thing on desktop or android( they are playing video directly continuously)

Actual result: on ios, play controls and player is shown

Expected result: can we improve this and make similar to android

---

**Reported by:** Vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672b4b09d6e3a230d68bcd54?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/use-cases/employee-engagement](https://na13-prezzee.webflow.io/en-us/use-cases/employee-engagement)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672b4b09d6e3a230d68bcd54?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Safari 18.0.1</td></tr><tr><td><strong>Screen Size</strong></td><td>375 x 812</td></tr><tr><td><strong>OS</strong></td><td>iOS 18.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>375 x 628</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;3x</td></tr></table>

**Comment by vinod-ku1989** [comment]
needs to be done on other particular use cases pages too where we have the videos in some sections

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672b4b09d6e3a230d68bcd54?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
