### ISSUE TITLE
[Marker.io] Flag

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#70]
[![Screenshot_2024-11-07_04-05-18.png](https://img.marker.io/s/672c3c7ebecc08a050278079/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjM2M3ZWJlY2MwOGEwNTAyNzgwNzkiLCJvd25lclJlc291cmNlVXVpZCI6IjFjYjY2YjhlLWE0Y2EtNGZhMy05MjVhLTJjMWQyOTJmYzM1MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6ImFkcmllbkBuYS5zdHVkaW8iLCJ0ZWFtVXVpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzEwMSwyNTEsMTI2LDE2MiwxMjUsMTU4LDE5MSwyMjksMTk5LDY4LDk5LDIzMV19LCJpYXQiOjE3MzA5NTIzMTgsImV4cCI6MTczODcyODMxOH0.hFX8kvVMzljrieEq-Kqd_5fd5e-EtAxBKOX8FvAWa8Y)](https://img.marker.io/s/672c3c7ebecc08a050278079/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjM2M3ZWJlY2MwOGEwNTAyNzgwNzkiLCJvd25lclJlc291cmNlVXVpZCI6IjFjYjY2YjhlLWE0Y2EtNGZhMy05MjVhLTJjMWQyOTJmYzM1MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6ImFkcmllbkBuYS5zdHVkaW8iLCJ0ZWFtVXVpZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzEwMSwyNTEsMTI2LDE2MiwxMjUsMTU4LDE5MSwyMjksMTk5LDY4LDk5LDIzMV19LCJpYXQiOjE3MzA5NTIzMTgsImV4cCI6MTczODcyODMxOH0.hFX8kvVMzljrieEq-Kqd_5fd5e-EtAxBKOX8FvAWa8Y)

Funnily enough it appears in screenshot but not on actual website on mobile - flags don’t show and the box is tiny. These should default to locale 

---

**Reported by:** Adrien (adrien@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672c3c7ebecc08a05027807c?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/contact](https://na13-prezzee.webflow.io/en-us/contact)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672c3c7ebecc08a05027807c?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Chrome Mobile 130.0.6723.90</td></tr><tr><td><strong>Screen Size</strong></td><td>375 x 812</td></tr><tr><td><strong>OS</strong></td><td>iOS 18.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>375 x 748</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;3x</td></tr></table>

**Comment by vinod-ku1989** [comment]
this is how it appears in real:
https://drive.google.com/file/d/1fnaE5aKXQGgPWvOgRaZlmz2XsP2CVDcO/view?usp=sharing

anotheralready raised issue :
https://github.com/NotAnother-NZ/na13-prezzee/issues/1

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672c3c7ebecc08a05027807c?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
