### ISSUE TITLE
[Marker.io] card results are not clickable

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#72]
[![Screenshot_2024-11-07_04-15-50.png](https://img.marker.io/s/672c3ef6bb1743111798a7b8/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjM2VmNmJiMTc0MzExMTc5OGE3YjgiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk1Mjk1MCwiZXhwIjoxNzM4NzI4OTUwfQ.ANS1WsQPznCxoZ9elZibfJ-nVATE5NKQTuAEYd0m3U0)](https://img.marker.io/s/672c3ef6bb1743111798a7b8/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjM2VmNmJiMTc0MzExMTc5OGE3YjgiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk1Mjk1MCwiZXhwIjoxNzM4NzI4OTUwfQ.ANS1WsQPznCxoZ9elZibfJ-nVATE5NKQTuAEYd0m3U0)

Steps to reproduce:
1) go to search page
2) search for keyword like "grill"
3) try to click on any results under the card

Actual result: card image or text below the card image are not clickable and nothing happens on clicking it

Expected result: user should be able to clickon card results.

( may be discuss with Christina- if both image and text should be clickable )

video:
https://go.screenpal.com/watch/cZXifhncJXl

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672c3ef6bb1743111798a7bb?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/search?query=grill](https://na13-prezzee.webflow.io/en-us/search?query=grill)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672c3ef6bb1743111798a7bb?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
@ckosik1 can you confirm on this please. if both images and text should be clickable under "card" results.?
so that @Druhin13 can fix accordingly.

**Comment by Druhin13** [comment]
entire card is the intended behavior

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672c3ef6bb1743111798a7bb?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
