### ISSUE TITLE
[Marker.io] images are not loading for certain pages on search results page

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#73]
[![Screenshot_2024-11-07_04-31-16.png](https://img.marker.io/s/672c4294e0b2dba53dd7831b/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjNDI5NGUwYjJkYmE1M2RkNzgzMWIiLCJvd25lclJlc291cmNlVXVpZCI6IjMxOTEyN2Y0LWIzZjctNDJmZC1iOTA5LTNjMjk5MmZhMzc3ZiIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk1Mzg3NiwiZXhwIjoxNzM4NzI5ODc2fQ.dhHxOIZ_l6eX6F1fNJd-k_9CNCcdshmtbT986E42BqQ)](https://img.marker.io/s/672c4294e0b2dba53dd7831b/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjNDI5NGUwYjJkYmE1M2RkNzgzMWIiLCJvd25lclJlc291cmNlVXVpZCI6IjMxOTEyN2Y0LWIzZjctNDJmZC1iOTA5LTNjMjk5MmZhMzc3ZiIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk1Mzg3NiwiZXhwIjoxNzM4NzI5ODc2fQ.dhHxOIZ_l6eX6F1fNJd-k_9CNCcdshmtbT986E42BqQ)

Steps to reproduce:
1)go to search page
2)search for employee
3) notice some results in page and articles section
4) click on that page result

Actual result:images are not loading even though the pageseems to have some image

Expected result: please check this once.not sure .if those images are coming up from other component on search results page.

https://go.screenpal.com/watch/cZXif0ncJ2n

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672c4294e0b2dba53dd7831e?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/search?query=employee](https://na13-prezzee.webflow.io/en-us/search?query=employee)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672c4294e0b2dba53dd7831e?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
probably it is related to configuration but please still check it if this is a bug cause the page seems to be having images but not the results on search results page.

**Comment by Druhin13** [comment]
need to make sure that all pages have an open graph share image set

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672c4294e0b2dba53dd7831e?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
