### ISSUE TITLE
[Marker.io] are we ok with display of the content above the nav bar when the user is scrolling down on page

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#75]
[![Screenshot_2024-11-07_04-39-39.png](https://img.marker.io/s/672c448b7e933733f6c9eb9d/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjNDQ4YjdlOTMzNzMzZjZjOWViOWQiLCJvd25lclJlc291cmNlVXVpZCI6IjMxOTEyN2Y0LWIzZjctNDJmZC1iOTA5LTNjMjk5MmZhMzc3ZiIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk1NDM3OSwiZXhwIjoxNzM4NzMwMzc5fQ.zRq89se9Q2yTZBE2uyKtcUmfll-c67DOacGJ_tbaS90)](https://img.marker.io/s/672c448b7e933733f6c9eb9d/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjNDQ4YjdlOTMzNzMzZjZjOWViOWQiLCJvd25lclJlc291cmNlVXVpZCI6IjMxOTEyN2Y0LWIzZjctNDJmZC1iOTA5LTNjMjk5MmZhMzc3ZiIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk1NDM3OSwiZXhwIjoxNzM4NzMwMzc5fQ.zRq89se9Q2yTZBE2uyKtcUmfll-c67DOacGJ_tbaS90)

Steps to reproduce:
1) onany page, scroll down and notice the area above the nav bar

Actual result: content is visible

Expected result: are we sure we want to display this above nav bar. or should we
1) completely hide it
2) blur it 

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672c448b7e933733f6c9eba0?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/search?query=employee](https://na13-prezzee.webflow.io/en-us/search?query=employee)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672c448b7e933733f6c9eba0?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
@ckosik1 please check this and assign it to @Druhin13 if we would like to address this

**Comment by ckosik1** [comment]
Intended

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672c448b7e933733f6c9eba0?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
