### ISSUE TITLE
[Marker.io] are we sure that only "view" button should take the user to the respective page on "search results"

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#76]
[![Screenshot_2024-11-07_04-49-55.png](https://img.marker.io/s/672c46f3bb1743111798c7e5/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjNDZmM2JiMTc0MzExMTc5OGM3ZTUiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk1NDk5NSwiZXhwIjoxNzM4NzMwOTk1fQ.gHPu8RpQVgQX7Eja4Uua3BU_S_w_b7Lldi8Olgepp_A)](https://img.marker.io/s/672c46f3bb1743111798c7e5/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjNDZmM2JiMTc0MzExMTc5OGM3ZTUiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk1NDk5NSwiZXhwIjoxNzM4NzMwOTk1fQ.gHPu8RpQVgQX7Eja4Uua3BU_S_w_b7Lldi8Olgepp_A)

Steps to reproduce:
1) on search results, seaarch for "Employee"
2) go to "pages and articles" section
3)try to click the image or title and description

Actual result: currently only "view" button takes theuserto respective page

Expected result:
should we make the "image" , "title" and "description" clickable too ?

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672c46f3bb1743111798c7e8?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/search?query=employee](https://na13-prezzee.webflow.io/en-us/search?query=employee)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672c46f3bb1743111798c7e8?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
@ckosik1 please have a look at this suggestion.
if we would like to do something abt this, assign it to @Druhin13 .

**Comment by ckosik1** [comment]
@vinod-ku1989 Thanks for the suggestion - It's intended
