### ISSUE TITLE
[Marker.io] (Mobile) there is no “show more” button present below the cards

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#79]
[![Screenshot_2024-11-07_05-06-54.png](https://img.marker.io/s/672c4aee738cd3b4ee6761a8/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjNGFlZTczOGNkM2I0ZWU2NzYxYTgiLCJvd25lclJlc291cmNlVXVpZCI6IjFmNTE1MzZkLTE0ZDQtNGE4Ni1iM2QzLWQ4MjBiNTBlYTk0MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk1NjAxNCwiZXhwIjoxNzM4NzMyMDE0fQ.4KayseQrlkKOurnQal704x8au00rKiMaPWt12revZP8)](https://img.marker.io/s/672c4aee738cd3b4ee6761a8/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjNGFlZTczOGNkM2I0ZWU2NzYxYTgiLCJvd25lclJlc291cmNlVXVpZCI6IjFmNTE1MzZkLTE0ZDQtNGE4Ni1iM2QzLWQ4MjBiNTBlYTk0MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk1NjAxNCwiZXhwIjoxNzM4NzMyMDE0fQ.4KayseQrlkKOurnQal704x8au00rKiMaPWt12revZP8)

Steps to reproduce:
1) on search page,search for food
2) see the results under cards section
3) compare with figma.there is no show more button on the page

Actual result: all results are visible.

Expected result: desktop design does not have it but mobile has

---

**Reported by:** Vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672c4aee738cd3b4ee6761ab?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/search?query=Food](https://na13-prezzee.webflow.io/en-us/search?query=Food)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672c4aee738cd3b4ee6761ab?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Safari 18.0.1</td></tr><tr><td><strong>Screen Size</strong></td><td>375 x 812</td></tr><tr><td><strong>OS</strong></td><td>iOS 18.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>375 x 710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;3x</td></tr></table>

**Comment by vinod-ku1989** [comment]
@ckosik1 please check this design discrepancy and confirm if that button should be there or not.

also, if it should be there, then how many results should be visible directly .

assign it to @Druhin13 later (if something needs to be fixed after your confirmation)

**Comment by Druhin13** [comment]
lazy load added | intended behavior
