### ISSUE TITLE
[Marker.io] suggestion: we can implement loading icon/progress icon untill the search results  are loaded

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#80]
[![Screenshot_2024-11-07_07-10-45.png](https://img.marker.io/s/672c67f57e933733f6ca9a10/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjNjdmNTdlOTMzNzMzZjZjYTlhMTAiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk2MzQ0NSwiZXhwIjoxNzM4NzM5NDQ1fQ.Q01Gkz--qCEraV11vXWiX46FychPPDLZSIIfWiOpUhU)](https://img.marker.io/s/672c67f57e933733f6ca9a10/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjNjdmNTdlOTMzNzMzZjZjYTlhMTAiLCJvd25lclJlc291cmNlVXVpZCI6IjY2Mzk1MmRhLTU0NTItNGY5YS05YTRjLTE4ZWJhNjUyZmQ4MyIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk2MzQ0NSwiZXhwIjoxNzM4NzM5NDQ1fQ.Q01Gkz--qCEraV11vXWiX46FychPPDLZSIIfWiOpUhU)

Steps to reproduce:
1) on search page, search  for any keyword
2)wait for results

Actual result: currently we do not have any loading icon or progress icon to indicate search is in progress

Expected result: i think we should implement this...there could be lot of results later on and it might take a bit of time for the results to load.

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672c67f57e933733f6ca9a13?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/search?query=food](https://na13-prezzee.webflow.io/en-us/search?query=food)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672c67f57e933733f6ca9a13?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 130.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
@ckosik1 @Druhin13 please look at this suggestion. and if needed ,discuss with Adrien.

**Comment by Druhin13** [comment]
we're moving to an instantaneous search instead
to be confirmed and updated soon

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672c67f57e933733f6ca9a13?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
