### ISSUE TITLE
[Marker.io] Suggestion: should we have pagination or “show more” button for “pages section too on search results page

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#82]
[![Screenshot_2024-11-07_07-24-13.png](https://img.marker.io/s/672c6b1de0b2dba53dd84b68/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjNmIxZGUwYjJkYmE1M2RkODRiNjgiLCJvd25lclJlc291cmNlVXVpZCI6IjE5Njk5MDdlLTNkZDAtNDE4ZS1hZGMzLTE4OGJhMWM1MTFlZiIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk2NDI1MywiZXhwIjoxNzM4NzQwMjUzfQ.todc1aND4wo_0dYluulahBm7Oi7Meld5ml2fexX7ItM)](https://img.marker.io/s/672c6b1de0b2dba53dd84b68/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjNmIxZGUwYjJkYmE1M2RkODRiNjgiLCJvd25lclJlc291cmNlVXVpZCI6IjE5Njk5MDdlLTNkZDAtNDE4ZS1hZGMzLTE4OGJhMWM1MTFlZiIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk2NDI1MywiZXhwIjoxNzM4NzQwMjUzfQ.todc1aND4wo_0dYluulahBm7Oi7Meld5ml2fexX7ItM)

Steps to reproduce:
1) on search results page, search for any keyword that would result in lot of page results

Actual result:there is no pagination or “show more” option right now. All results are shown directly and user would keep on scrolling

Expected result: should we have pagination or show more button ( hiding some of the results)

---

**Reported by:** Vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672c6b1de0b2dba53dd84b6b?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/search?query=How+Employee+Recognition+Can+Boost+Morale+and+Productivity+%7C+Prezzee+Blogs](https://na13-prezzee.webflow.io/en-us/search?query=How+Employee+Recognition+Can+Boost+Morale+and+Productivity+%7C+Prezzee+Blogs)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672c6b1de0b2dba53dd84b6b?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>tablet</td></tr><tr><td><strong>Browser</strong></td><td>Safari 17.7</td></tr><tr><td><strong>Screen Size</strong></td><td>768 x 1024</td></tr><tr><td><strong>OS</strong></td><td>iOS 17.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1024 x 729</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by vinod-ku1989** [comment]
@ckosik1 please check this.
(as pointed out in another bug. "mobile design" shows "Show more" button for cards section but desktop does not have that.also "show more" is not present for "pages and articles" section on search results page.

if we would like to implement this, assign it to @Druhin13 ( with final change that needs to be added)

**Comment by Druhin13** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/672c6b1de0b2dba53dd84b6b?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
