### ISSUE TITLE
[Marker.io] date is missing on blog card tiles on blog page

### ISSUE THREAD

**Issue by Druhin13** [NotAnother-NZ/na13-prezzee#83]
[![Screenshot_2024-11-07_10-20-51.png](https://img.marker.io/s/672c9483bb174311179af22f/2?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjOTQ4M2JiMTc0MzExMTc5YWYyMmYiLCJvd25lclJlc291cmNlVXVpZCI6IjRhMjkzNjNkLTFjZmQtNGRlZS1hNzkyLTlmMzhiNWFhODVlYSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk3NDg1MSwiZXhwIjoxNzM4NzUwODUxfQ.ZTvWRARYMf79SvgIt-UGOv-5StNqXKps_BrG1ye0KuM)](https://img.marker.io/s/672c9483bb174311179af22f/0?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRSZXNvdXJjZSI6InNjcmVlbnNob3QiLCJyZXNvdXJjZVV1aWQiOiI2NzJjOTQ4M2JiMTc0MzExMTc5YWYyMmYiLCJvd25lclJlc291cmNlVXVpZCI6IjRhMjkzNjNkLTFjZmQtNGRlZS1hNzkyLTlmMzhiNWFhODVlYSIsIm93bmVyUmVzb3VyY2VFbWFpbCI6InZpbm9kQG5hLnN0dWRpbyIsInRlYW1VdWlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbMTAxLDI1MSwxMjYsMTYyLDEyNSwxNTgsMTkxLDIyOSwxOTksNjgsOTksMjMxXX0sImlhdCI6MTczMDk3NDg1MSwiZXhwIjoxNzM4NzUwODUxfQ.ZTvWRARYMf79SvgIt-UGOv-5StNqXKps_BrG1ye0KuM)

Steps to reproduce:
1) go to https://na13-prezzee.webflow.io/en-us/blog
2) scroll down and notice the different tiles, compare with figma

Actual result:
date is missing

Expected result: if current behaviour is correct, then ignore else fix this and format shouldmatch figma

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/672c9483bb174311179af232?advanced=1&comments=1)

**Source URL:** [https://na13-prezzee.webflow.io/en-us/blog](https://na13-prezzee.webflow.io/en-us/blog)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/672c9483bb174311179af232?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 132.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 615</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by ckosik1** [comment]
Intended
